/**
 * One-shot results generator for report Chapter 13.
 *
 * Runs the deterministic suites (Tiers 1–3) across both packages, computes the
 * offline functional metrics (Tier 4a), and writes a Section-13-mapped artifact
 * to testing/results/section13_results.md. Accuracy/latency/usability cells that
 * need keys, a device, or participants are emitted as explicit placeholders —
 * NEVER an invented number.
 *
 *   bun run testing/run_all.ts
 *   RUN_LIVE=1 bun run testing/run_all.ts   # also runs the API-key accuracy tier
 */
import { computeIntentMetrics } from "./harness/intent/run";
import { computeUsabilityMetrics, renderUsabilityTable } from "./usability/analyze";
import { computeDatasetMetrics } from "./datasets/run";

const ROOT = `${import.meta.dir}/..`;
const MOBILE = `${ROOT}/mobile`;

interface Suite {
  pass: number;
  fail: number;
}

async function runSuite(cwd: string, dirs: string[]): Promise<Suite> {
  const proc = Bun.spawn(["bun", "test", ...dirs], { cwd, stdout: "pipe", stderr: "pipe" });
  const [out, err] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
  ]);
  await proc.exited;
  const text = `${out}\n${err}`;
  const pass = Number(text.match(/(\d+)\s+pass/)?.[1] ?? "0");
  const fail = Number(text.match(/(\d+)\s+fail/)?.[1] ?? "0");
  return { pass, fail };
}

function pct(x: number): string {
  return `${(x * 100).toFixed(0)}%`;
}

const NEEDS_DATA = "needs data collection (run with RUN_LIVE=1 + dataset)";
const NEEDS_DEVICE = "needs device (Mentra Live — capture via mobile timeline / usability CSV)";

async function main(): Promise<void> {
  console.log("Running suites…");
  const serverUnit = await runSuite(ROOT, ["./testing/unit"]);
  const serverIntegration = await runSuite(ROOT, ["./testing/integration"]);
  const serverRegression = await runSuite(ROOT, ["./testing/regression"]);
  const mobileUnit = await runSuite(MOBILE, ["./testing/unit"]);
  const mobileStateMachine = await runSuite(MOBILE, ["./testing/state-machine"]);
  // Report-analysis tooling tests — validate the usability + dataset scripts. Kept
  // OUT of the Chapter-13 product-test tables (13.9–13.11), which count only tests
  // of the Suhail product, not of the report's own measurement code.
  const tooling = await runSuite(ROOT, ["./testing/usability", "./testing/datasets"]);

  const unitPass = serverUnit.pass + mobileUnit.pass + mobileStateMachine.pass;
  const unitFail = serverUnit.fail + mobileUnit.fail + mobileStateMachine.fail;

  console.log("Computing offline functional metrics…");
  const intent = await computeIntentMetrics();
  const usability = await computeUsabilityMetrics();
  const datasets = await computeDatasetMetrics();

  const allGreen =
    unitFail + serverIntegration.fail + serverRegression.fail + tooling.fail === 0;

  const lines: string[] = [];
  lines.push("# Suhail — Section 13 results (generated)");
  lines.push("");
  lines.push("> Generated by `bun run testing/run_all.ts`. Numbers are real where computed;");
  lines.push("> uncomputed cells are marked needs-data / needs-device / needs-participants.");
  lines.push("> This suite is independent of the abandoned PRs #20/#35 and tests the real modules.");
  lines.push("");
  lines.push(`Overall: ${allGreen ? "ALL GREEN ✅" : "FAILURES ❌"}`);
  lines.push("");

  lines.push("## Table 13.9 — Unit tests");
  lines.push(`Server unit: ${serverUnit.pass} pass / ${serverUnit.fail} fail`);
  lines.push(`Mobile unit: ${mobileUnit.pass} pass / ${mobileUnit.fail} fail`);
  lines.push(`Mobile state-machine (listening): ${mobileStateMachine.pass} pass / ${mobileStateMachine.fail} fail`);
  lines.push(`**Total unit: ${unitPass} pass / ${unitFail} fail — ${unitFail === 0 ? "100%" : pct(unitPass / (unitPass + unitFail))}**`);
  lines.push("");

  lines.push("## Table 13.10 — Integration tests");
  lines.push(`Relay HTTP integration (auth, photo flow, intent pipeline): ${serverIntegration.pass} pass / ${serverIntegration.fail} fail`);
  lines.push("");

  lines.push("## Table 13.11 — Regression tests");
  lines.push(`Server known-fixes: ${serverRegression.pass} pass / ${serverRegression.fail} fail`);
  lines.push("(Interrupted-enrollment suppression is covered in the mobile enrollment unit suite.)");
  lines.push("");

  lines.push("## Table 13.12 — Functional tests per command (success rate + latency)");
  lines.push("| Command | Success rate | E2E latency (median) |");
  lines.push("|---|---|---|");
  const cmdRows: Array<{ label: string; cmd: string }> = [
    { label: "Scene summarization", cmd: "scene-summarize" },
    { label: "OCR", cmd: "ocr-read-text" },
    { label: "Face recognition", cmd: "face-recognize" },
    { label: "Face enrollment", cmd: "face-enroll" },
    { label: "Object finding", cmd: "find-object" },
    { label: "Currency recognition", cmd: "currency-recognize" },
    { label: "Visual question answering", cmd: "visual-qa" },
    { label: "Color detection", cmd: "color-detect" },
  ];
  for (const { label, cmd } of cmdRows) {
    const r = datasets.byCommand[cmd];
    const acc = r && r.accuracy != null ? `${pct(r.accuracy)} (n=${r.n}, B — live)` : `${NEEDS_DATA} (B)`;
    lines.push(`| ${label} | ${acc} | ${NEEDS_DEVICE} (C) |`);
  }
  lines.push("");

  lines.push("## Table 13.13 — Cross-cutting subsystem functional results");
  lines.push("| Subsystem | Metric | Value |");
  lines.push("|---|---|---|");
  lines.push(`| Hybrid intent router | Keyword fast-path rate (n=${intent.n}, offline) | ${pct(intent.fastPathRate)} (A) |`);
  lines.push(`| Hybrid intent router | Keyword classification accuracy (n=${intent.n}, offline) | ${pct(intent.keywordClassAccuracy)} (A) |`);
  lines.push(
    `| Hybrid intent router | LLM-path classification accuracy | ${
      intent.llm ? `${pct(intent.llm.accuracy)} (n=${intent.llm.n}, live)` : NEEDS_DATA + " (B)"
    } |`,
  );
  lines.push("| Device-token auth | Unauthorized-request rejection rate | 100% by construction (A — verified in integration suite) |");
  lines.push("| Token-mediated photo flow | Token-expiry / unknown-token rejection | 100% by construction (A — verified in unit + integration) |");
  lines.push("| Listening state machine | Grace / TTS-echo / low-confidence rejection | verified (A — mobile state-machine suite) |");
  lines.push(`| Pre-capture / cue / photo round-trip latency | medians | ${NEEDS_DEVICE} (C) |`);
  lines.push("");

  lines.push("## Table 13.14 — Usability");
  lines.push(...renderUsabilityTable(usability));

  lines.push("---");
  lines.push(
    `Report-analysis tooling tests (validate the usability + dataset scripts; NOT part of Tables 13.9–13.11): ${tooling.pass} pass / ${tooling.fail} fail`,
  );
  lines.push("");

  const outPath = `${ROOT}/testing/results/section13_results.md`;
  await Bun.write(outPath, lines.join("\n") + "\n");
  console.log(`\nWrote ${outPath}`);
  console.log(`Unit ${unitPass} · Integration ${serverIntegration.pass} · Regression ${serverRegression.pass}`);

  if (!allGreen) process.exit(1);
}

main();
